version: 2
jobs:
  build:
    working_directory: ~/aerogear
    docker:
      # Node 8 LTS
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: clone-sdk
          command: git clone --depth 1 https://github.com/aerogear/aerogear-js-sdk sdk
      - run:
          name: run sdk build
          working_directory: ./sdk
          command: npm i && npm run bootstrap && npm run build
      - run:
          name: Remove aerogear packages
          command: rm -rf node_modules/@aerogear && mkdir node_modules/@aerogear
      - run:
          name: link-sdk
          working_directory: ./node_modules/@aerogear
          command: ln -s ../../sdk/packages/auth auth && ln -s ../../sdk/packages/core core && ln -s ../../sdk/packages/app app && ln -s ../../sdk/packages/security security && ln -s ../../sdk/packages/push push
      - run:
          name: run build
          command: npm run build
      - run:
          name: run lint
          command: npm run lint

